MCU=attiny85 //Type of AVR chip used
AVRDUDEMCU=t85
CC=/usr/bin/avr-gcc //Where the program is saved on my raspberry pi 3b
CFLAGS=-g -Os -Wall -mcall-prologues -mmcu=$(MCU)
OBJ2HEX=/usr/bin/avr-objcopy
AVRDUDE=/usr/bin/avrdude //AVRDUDE exe location (which avrdude)
TARGET=ssc //The name of the C file

all : 
    $(CC) $(CFLAGS) $(TARGET).c -o $(TARGET)
    $(OBJ2HEX) -R .eeprom -O ihex $(TARGET) $(TARGET).hex
    rm -f $(TARGET)
  
install : all
    sudo gpio -g mode 22 out
    sudo gpio -g write 22 0
    sudo $(AVRDUDE) -p $(AVRDUDEMCU) -P /dev/spidev0.0 -c linuxspi -b 10000 -U flash:w:$(TARGET).hex
    sudo gpio -g write 22 1
  
noreset : all
    sudo $(AVRDUDE) -p $(AVRDUDEMCU) -P /dev/spidev0.0 -c linuxspi -b 10000 -U flash:w:$(TARGET).hex
    
fuse : 
    sudo gpio -g mode 22 out
    sudo gpio -g write 22 0
    sudo $(AVRDUDE) -p $(AVRDUDEMCU) -P /dev/spidev0.0 -c linuxspi -b 10000 -U lfuse:w:0x62:m -U hfuse:w:0xdf:m -U efuse:w:0xff:m
    sudo gpio -g write 22 1
    
turnoff :
    sudo gpio -g write 22 0
    
clean :
    rm -f *.hex *.obj *.o

charm :
    make
    make install
    make fuse
    make clean
